# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darby CAT Club
email: jm8hjkl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's a club about Computer and Technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://darbycat.github.io" # the base hostname & protocol for your site
twitter_username: no
github_username:  jm8

# Build settings
markdown: kramdown
